"""Query Engine: 構造化された文章検索DSL。"""
from __future__ import annotations

from query_engine.adapters import (
    AccessAdapter,
    BrowserPage,
    CsvAdapter,
    JsonAdapter,
    PandasAdapter,
    TextDocument,
    access_to_documents,
    browser_page_to_document,
    csv_to_documents,
    dataframe_to_documents,
    dataframe_to_records,
    extract_text_file,
    from_text,
    from_text_file,
    json_to_documents,
    load_access,
    load_csv,
    load_json,
    log_to_document,
    normalize_text,
    row_to_document,
    rows_to_documents,
)
from query_engine.ast import (
    AndNode,
    CompareNode,
    EmptyNode,
    FieldNode,
    NotNode,
    OrNode,
    PhraseNode,
    QueryNode,
    RegexNode,
    TermNode,
)
from query_engine.evaluators.memory import match_query, search
from query_engine.evaluators.sql import SqlCompileResult, compile_sql_where
from query_engine.models import SearchQuery, SearchResult, SortSpec
from query_engine.parser import GRAMMAR, QuerySyntaxError, parse, parse_query, tokenize

__all__: list[str] = [
    "AndNode",
    "AccessAdapter",
    "BrowserPage",
    "CompareNode",
    "CsvAdapter",
    "EmptyNode",
    "FieldNode",
    "GRAMMAR",
    "JsonAdapter",
    "NotNode",
    "OrNode",
    "PandasAdapter",
    "PhraseNode",
    "QueryNode",
    "QuerySyntaxError",
    "RegexNode",
    "SearchQuery",
    "SearchResult",
    "SqlCompileResult",
    "SortSpec",
    "TermNode",
    "TextDocument",
    "access_to_documents",
    "browser_page_to_document",
    "compile_sql_where",
    "csv_to_documents",
    "dataframe_to_documents",
    "dataframe_to_records",
    "extract_text_file",
    "from_text",
    "from_text_file",
    "json_to_documents",
    "load_access",
    "load_csv",
    "load_json",
    "log_to_document",
    "match_query",
    "normalize_text",
    "parse",
    "parse_query",
    "row_to_document",
    "rows_to_documents",
    "search",
    "tokenize",
]
